### PR TITLE
PL-433: Update Employee icon

### PR DESCRIPTION
**Pull request by mbednarcik**
This PR updates the small employee icon in our font in unified assets. 

image

image

### CODE REVIEW

**Comment by jahvon** [comment]
This looks good to me! However, the icon seems off-center next to "Teacher Summary". That icon may have always been off but is just more noticeable with this new icon. I don't think that should be a major concern for rolling this out though. Might be some small tweaking at another point?

**Comment by mbednarcik** [comment]
> This looks good to me! However, the icon seems off-center next to "Teacher Summary". That icon may have always been off but is just more noticeable with this new icon. I don't think that should be a major concern for rolling this out though. Might be some small tweaking at another point?

Yeah, it looks like the old icon was also off-centered? 
screen shot 2019-03-04 at 3 58 17 pm

**Comment by jahvon** [comment]
> > This looks good to me! However, the icon seems off-center next to "Teacher Summary". That icon may have always been off but is just more noticeable with this new icon. I don't think that should be a major concern for rolling this out though. Might be some small tweaking at another point?
> 
> Yeah, it looks like the old icon was also off-centered?
> screen shot 2019-03-04 at 3 58 17 pm

Yup, I think that the CSS in rainbow needs to be changed to fix this.

**Comment by geoffreylitt** [comment]
@mbednarcik this new icon looks slightly larger than the others when it shows up in the app. I think there may be an issue where the asset that @zhuxingjie gave us doesn't match the dimensions of the other icon files.

Do you think you could try redoing the process with the new asset that Roger shared in this thread? (it's the last file in that thread):

https://panoramaed.slack.com/archives/CGARMUXMZ/p1551728703006400

Sorry about that, hope it's not too much work to retry with the new asset.

**Comment by mbednarcik** [comment]
> @mbednarcik this new icon looks slightly larger than the others when it shows up in the app. I think there may be an issue where the asset that @zhuxingjie gave us doesn't match the dimensions of the other icon files.
> 
> Do you think you could try redoing the process with the new asset that Roger shared in this thread? (it's the last file in that thread):
> 
> https://panoramaed.slack.com/archives/CGARMUXMZ/p1551728703006400
> 
> Sorry about that, hope it's not too much work to retry with the new asset.

image
Looks much better!

**Pull request merged**
